### PR TITLE
Run pytest included with rtree

### PR DESCRIPTION
**Pull request by mwtoews**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

---

This PR runs the upstream rtree tests with pytest. It is called within the existing run_test.py script.

### CODE REVIEW

**Comment by hobu** [comment]
We seem to be not very happy on pypy

**Comment by mwtoews** [comment]
There are actually two issues. One issue is [tracked upstream](https://github.com/Toblerity/rtree/issues/324), and skipped here for PyPy.

However, the second issue is a segmentation fault while running pytest on some PyPy platforms e.g.
```
===== testing package: rtree-1.3.0-py39h2fb8f80_1 =====
running run_test.py
============================= test session starts ==============================
platform linux -- Python 3.9.18[pypy-7.3.15-final], pytest-8.2.2, pluggy-1.5.0 -- $PREFIX/bin/python
cachedir: .pytest_cache
rootdir: $SRC_DIR
/home/conda/feedstock_root/build_artifacts/rtree_1720650761615/test_tmp/conda_test_runner.sh: line 3:  1280 Segmentation fault      (core dumped) "/home/conda/feedstock_root/build_artifacts/rtree_1720650761615/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python" -s "/home/conda/feedstock_root/build_artifacts/rtree_1720650761615/test_tmp/run_test.py"
WARNING: Tests failed for rtree-1.3.0-py39h2fb8f80_1.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: rtree-1.3.0-py39h2fb8f80_1.conda
```
For instance, this issue:

- seg fault with linux_aarch64_numpy1.22python3.9.____73_pypy
- clean run with linux_64_numpy1.22python3.9.____73_pypy

It could be due to [the awkwardness](https://doc.pypy.org/en/latest/faq.html#what-about-numpy-numpypy-micronumpy) of numpy with pypy. I'll try once more to see if pytest can run only with PyPy on linux_64...

**Comment by hobu** [comment]
please merge this when you're happy with it. I don't know that we officially supported pypy with Rtree anyway.

**Comment by mwtoews** [comment]
Lets keep the test for now, but if PyPy acts up in the future, then we can remove the test and decide to disable PyPy support.

**Pull request merged**
