### PR TITLE
PR: Enable arch64 build

### PR DESCRIPTION
**Pull request by steff456**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Hi @ocefpaf!

As you've seen in other feedstocks I'm trying to add builds for arch64 of Spyder and Spyder-terminal and this is one dependency that needs to enable that build as well. Hope you approve the changes!

### CODE REVIEW

**Comment by steff456** [comment]
@conda-forge-admin, please rerender

**Comment by hobu** [comment]
Please update this PR to ditch Python 3.6 and I'll be happy to merge it. I don't know why RTree is behaving differently for 3.6 and it doesn't seem worth it to find out.

**Comment by steff456** [comment]
@conda-forge-admin, please rerender

**Comment by steff456** [comment]
@conda-forge-admin, please rerender

**Comment by steff456** [comment]
@hobu this is ready! Thank you so much for all your help with these packages 📦

**Pull request merged**
